<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE ISBNRangeMessage [
<!ELEMENT ISBNRangeMessage (MessageSource?, MessageSerialNumber?, MessageDate, EAN.UCCPrefixes, RegistrationGroups) >
<!ELEMENT MessageSource (#PCDATA) >
<!ELEMENT MessageSerialNumber (#PCDATA) >
<!ELEMENT MessageDate (#PCDATA) >
<!ELEMENT EAN.UCCPrefixes (EAN.UCC+) >
<!ELEMENT RegistrationGroups (Group+) >
<!ELEMENT EAN.UCC (Prefix, Agency, Rules) >
<!ELEMENT Group (Prefix, Agency, Rules) >
<!ELEMENT Rules (Rule+) >
<!ELEMENT Rule (Range, Length) >
<!ELEMENT Prefix (#PCDATA) >
<!ELEMENT Agency (#PCDATA) >
<!ELEMENT Range (#PCDATA) >
<!ELEMENT Length (#PCDATA) >
]>
<ISBNRangeMessage>
  <MessageSource>International ISBN Agency</MessageSource>
  <MessageSerialNumber>e8f94067-023b-42f2-bf59-78908f4a9ad5</MessageSerialNumber>
  <MessageDate>Thu, 15 Dec 2016 11:35:01 CET</MessageDate>
  <EAN.UCCPrefixes>
    <EAN.UCC>
      <Prefix>978</Prefix>
      <Agency>International ISBN Agency</Agency>
      <Rules>
        <Rule>
          <Range>0000000-5999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>6000000-6499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6500000-6999999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>7000000-7999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>8000000-9499999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>9500000-9899999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>9900000-9989999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9990000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </EAN.UCC>
    <EAN.UCC>
      <Prefix>979</Prefix>
      <Agency>International ISBN Agency</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>1000000-1299999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1300000-9999999</Range>
          <Length>0</Length>
        </Rule>
      </Rules>
    </EAN.UCC>
  </EAN.UCCPrefixes>
  <RegistrationGroups>
    <Group>
      <Prefix>978-0</Prefix>
      <Agency>English language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-2279999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>2280000-2289999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>2290000-6479999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6480000-6489999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>6490000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-1</Prefix>
      <Agency>English language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-3999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4000000-5499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>5500000-7319999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7320000-7399999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>7400000-8697999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8698000-9729999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9730000-9877999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9878000-9989999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9990000-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-2</Prefix>
      <Agency>French language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-3499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>3500000-3999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>4000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8400000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9199429</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9199430-9199689</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9199690-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-3</Prefix>
      <Agency>German language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0299999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0300000-0339999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>0340000-0369999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>0370000-0399999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>0400000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9539999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9540000-9699999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9700000-9899999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9900000-9949999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9950000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-4</Prefix>
      <Agency>Japan</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-5</Prefix>
      <Agency>former U.S.S.R</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0049999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>0050000-0099999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>0100000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-4209999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4210000-4299999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4300000-4309999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4310000-4399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4400000-4409999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4410000-4499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4500000-6039999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6040000-6049999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>6050000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9099999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9100000-9199999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9200000-9299999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9300000-9499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9500000-9500999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9501000-9799999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9800000-9899999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9900000-9909999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9910000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-600</Prefix>
      <Agency>Iran</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-4999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-601</Prefix>
      <Agency>Kazakhstan</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8500000-9999999</Range>
          <Length>2</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-602</Prefix>
      <Agency>Indonesia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0799999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0800000-0899999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>0900000-1099999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>1100000-1199999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>1200000-1399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>1400000-1499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>1500000-1699999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>1700000-1799999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>1800000-1899999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>1900000-1999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>2000000-5999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6000000-6199999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>6200000-6749999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6750000-6999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>7000000-7499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7500000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-603</Prefix>
      <Agency>Saudi Arabia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0499999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0500000-4999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-604</Prefix>
      <Agency>Vietnam</Agency>
      <Rules>
        <Rule>
          <Range>0000000-4999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>5000000-8999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>9000000-9799999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>9800000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-605</Prefix>
      <Agency>Turkey</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0099999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>0100000-0299999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0300000-0399999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>0400000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-3999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4000000-5999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6000000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-606</Prefix>
      <Agency>Romania</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>1000000-4999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-9099999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9100000-9199999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>9200000-9749999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9750000-9999999</Range>
          <Length>3</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-607</Prefix>
      <Agency>Mexico</Agency>
      <Rules>
        <Rule>
          <Range>0000000-3999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4000000-7499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7500000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-608</Prefix>
      <Agency>Macedonia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>1000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-4499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4500000-6499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6500000-6999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7000000-9999999</Range>
          <Length>1</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-609</Prefix>
      <Agency>Lithuania</Agency>
      <Rules>
        <Rule>
          <Range>0000000-3999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-611</Prefix>
      <Agency>Thailand</Agency>
      <Rules>
        <Rule>
          <Range>0000000-9999999</Range>
          <Length>0</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-612</Prefix>
      <Agency>Peru</Agency>
      <Rules>
        <Rule>
          <Range>0000000-2999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>3000000-3999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4000000-4499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4500000-4999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>5000000-9999999</Range>
          <Length>2</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-613</Prefix>
      <Agency>Mauritius</Agency>
      <Rules>
        <Rule>
          <Range>0000000-9999999</Range>
          <Length>1</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-614</Prefix>
      <Agency>Lebanon</Agency>
      <Rules>
        <Rule>
          <Range>0000000-3999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-615</Prefix>
      <Agency>Hungary</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-4999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>0</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-616</Prefix>
      <Agency>Thailand</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-617</Prefix>
      <Agency>Ukraine</Agency>
      <Rules>
        <Rule>
          <Range>0000000-4999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>5000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-618</Prefix>
      <Agency>Greece</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-4999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-619</Prefix>
      <Agency>Bulgaria</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1499999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1500000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-620</Prefix>
      <Agency>Mauritius</Agency>
      <Rules>
        <Rule>
          <Range>0000000-9999999</Range>
          <Length>1</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-621</Prefix>
      <Agency>Philippines</Agency>
      <Rules>
        <Rule>
          <Range>0000000-2999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>3000000-3999999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>4000000-5999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6000000-7999999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9499999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-7</Prefix>
      <Agency>China, People's Republic</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-4999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>6</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-80</Prefix>
      <Agency>former Czechoslovakia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>6</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-81</Prefix>
      <Agency>India</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>6</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-82</Prefix>
      <Agency>Norway</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6899999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6900000-6999999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>7000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9899999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9900000-9999999</Range>
          <Length>6</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-83</Prefix>
      <Agency>Poland</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-5999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6000000-6999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>6</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-84</Prefix>
      <Agency>Spain</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1399999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1400000-1499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>1500000-1999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9199999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9200000-9239999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9240000-9299999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9300000-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9699999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9700000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-85</Prefix>
      <Agency>Brazil</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-5499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5500000-5999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6000000-6999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9249999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9250000-9449999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9450000-9599999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9600000-9799999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>9800000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-86</Prefix>
      <Agency>former Yugoslavia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-2999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>3000000-5999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6000000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>6</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>